<?xml version="1.0" encoding="utf-8"?><Database Name="CRMSDD" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=3.131.105.103;Initial Catalog=CRMSDD;User ID=crmsdd" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="CRMSDDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PaymentTermId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsOldCompany" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Company_Branch" Member="Branches" ThisKey="CompanyId" OtherKey="CompanyId" Type="Branch" />
      <Association Name="Company_CompanySharedWith" Member="CompanySharedWiths" ThisKey="CompanyId" OtherKey="CompanyId" Type="CompanySharedWith" />
      <Association Name="Company_CompanyTag" Member="CompanyTags" ThisKey="CompanyId" OtherKey="CompanyId" Type="CompanyTag" />
    </Type>
  </Table>
  <Table Name="dbo.AddressTypeMaster" Member="AddressTypeMasters">
    <Type Name="AddressTypeMaster">
      <Column Name="AddressTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddressTypeName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AddressTypeMaster_AddressTypeMaster" Member="AddressTypeMaster2" ThisKey="AddressTypeId" OtherKey="AddressTypeId" Type="AddressTypeMaster" Cardinality="One" />
      <Association Name="AddressTypeMaster_BranchAddress" Member="BranchAddresses" ThisKey="AddressTypeId" OtherKey="AddressTypeId" Type="BranchAddress" />
      <Association Name="AddressTypeMaster_AddressTypeMaster" Member="AddressTypeMaster1" ThisKey="AddressTypeId" OtherKey="AddressTypeId" Type="AddressTypeMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Branch" Member="Branches">
    <Type Name="Branch">
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsHeadOffice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Branch_BranchAddress" Member="BranchAddresses" ThisKey="BranchId" OtherKey="BranchId" Type="BranchAddress" />
      <Association Name="Branch_BranchContact" Member="BranchContacts" ThisKey="BranchId" OtherKey="BranchId" Type="BranchContact" />
      <Association Name="Branch_BranchMember" Member="BranchMembers" ThisKey="BranchId" OtherKey="BranchId" Type="BranchMember" />
      <Association Name="Company_Branch" Member="Company" ThisKey="CompanyId" OtherKey="CompanyId" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BranchAddresses" Member="BranchAddresses">
    <Type Name="BranchAddress">
      <Column Name="BranchAddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddressTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="AddressTypeMaster_BranchAddress" Member="AddressTypeMaster" ThisKey="AddressTypeId" OtherKey="AddressTypeId" Type="AddressTypeMaster" IsForeignKey="true" />
      <Association Name="Branch_BranchAddress" Member="Branch" ThisKey="BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BranchContact" Member="BranchContacts">
    <Type Name="BranchContact">
      <Column Name="BranchPhoneNumberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Branch_BranchContact" Member="Branch" ThisKey="BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BranchMembers" Member="BranchMembers">
    <Type Name="BranchMember">
      <Column Name="BranchMemberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsPrimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsPermissionsInherit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Startdate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Branch_BranchMember" Member="Branch" ThisKey="BranchId" OtherKey="BranchId" Type="Branch" IsForeignKey="true" />
      <Association Name="Member_BranchMember" Member="Member" ThisKey="MemberId" OtherKey="MemberId" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanySharedWith" Member="CompanySharedWiths">
    <Type Name="CompanySharedWith">
      <Column Name="CompanySharedWithId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SharedWithId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Company_CompanySharedWith" Member="Company" ThisKey="CompanyId" OtherKey="CompanyId" Type="Company" IsForeignKey="true" />
      <Association Name="User_CompanySharedWith" Member="User" ThisKey="SharedWithId" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyTags" Member="CompanyTags">
    <Type Name="CompanyTag">
      <Column Name="CompanyTagsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagsMappingId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Company_CompanyTag" Member="Company" ThisKey="CompanyId" OtherKey="CompanyId" Type="Company" IsForeignKey="true" />
      <Association Name="TagsMaster_CompanyTag" Member="TagsMaster" ThisKey="TagsMappingId" OtherKey="TagsMasterId" Type="TagsMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="MemberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IsUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsOldMember" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Member_BranchMember" Member="BranchMembers" ThisKey="MemberId" OtherKey="MemberId" Type="BranchMember" />
      <Association Name="Member_PersonPhone" Member="PersonPhones" ThisKey="MemberId" OtherKey="MemberID" Type="PersonPhone" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentTermsMaster" Member="PaymentTermsMasters">
    <Type Name="PaymentTermsMaster">
      <Column Name="PaymentTermId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentTermName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PersonPhone" Member="PersonPhones">
    <Type Name="PersonPhone">
      <Column Name="PhoneID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPrimary" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Member_PersonPhone" Member="Member" ThisKey="MemberID" OtherKey="MemberId" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TagsMaster" Member="TagsMasters">
    <Type Name="TagsMaster">
      <Column Name="TagsMasterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TagsMaster_CompanyTag" Member="CompanyTags" ThisKey="TagsMasterId" OtherKey="TagsMappingId" Type="CompanyTag" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsEmailConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Phonenumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_CompanySharedWith" Member="CompanySharedWiths" ThisKey="UserID" OtherKey="SharedWithId" Type="CompanySharedWith" />
    </Type>
  </Table>
  <Table Name="dbo.ExceptionLog" Member="ExceptionLogs">
    <Type Name="ExceptionLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExceptionMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExceptionStackTrace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LogTimestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>